### ISSUE TITLE
issues with Random.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/dot#103]
Some issues with Random.js

- [x] this.seed is not defined in constructor and has no visibility annotation where it's defined in setSeed
- [x] this.seedrandom is not defined in constructor and has no visibility annotation where it's defined in setSeed
- [x] missing visibility annotations for several methods
- [x] there is no getSeed method
- [x] Math.setrandom is not documented, and apparently is a 3rd-party monkey patch

**Comment by pixelzoom** [comment]
All issues addressed in the above commit. @ariel-phet please assign someone to review.  The authors listed in the source code are:

```js
 * @author John Blanco (PhET Interactive Simulations)
 * @author Aaron Davis (PhET Interactive Simulations)
 * @author Sam Reid (PhET Interactive Simulations)
 * @author Mohamed Safi
```

**Comment by ariel-phet** [comment]
@samreid will review

**Comment by samreid** [comment]
The commits look straightforward and correct.  I additionally converted to an ES6 class and used an arrow function (after confirming there are no `inherit( Random` occurrences.

It looks like there is an additional opportunity to clean up because there is no usage of `setSeed`.  I'll look at that next.

**Comment by samreid** [comment]
Review complete, everything looks good.  Back to @pixelzoom to review changes made during the review.

**Comment by pixelzoom** [comment]
👍🏻 closing.
