### ISSUE TITLE
Matrix.QRDecomposition.solve is returning NaN

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#43]
I'm running unit tests for CCK as part of its matrix solve step.  For the same inputs, Jama is giving result matrix

```
1
0
4
```

and dot is giving
```
NaN
NaN
NaN
```

I have tracked the problem down to the matrix constructor call at the end of the QR solve method.  Dot currently has:

```js
      return new dot.Matrix( X, this.n, nx ).getMatrix( 0, this.n - 1, 0, nx - 1 );
```

But it looks like this constructor is not supported at the moment.  Changing the constructor call to:

```js
return new dot.Matrix( this.n, nx, X, true ).getMatrix( 0, this.n - 1, 0, nx - 1 );
```

Seems to solve the problem, and the new output is:
```
0.9999999403953552 
-1.1920928955078125e-7 
3.999999761581421 
```

I'd like to fix this soon so I can use this code for CCK, but I'm not aware of how widely this is used or if this fix for CCK could cause problems elsewhere somehow.  @jonathanolson can you take a look?

**Comment by samreid** [comment]
I committed the proposed fix above, but it should still be discussed with @jonathanolson.  @jbphet may also need to be aware of it depending on how he plans to deploy the next batch of RC test sims.

**Comment by jonathanolson** [comment]
Shouldn't affect anything I'm aware of. Is @jbphet using this?

**Comment by jbphet** [comment]
I'm not using Matrix.QRDecomposition.solve directly in any simulation code.  I think @samreid may have brought me into this discussion because he knows that I have several simulations that are poised for re-release and wants to make sure that I'd be working from a stable base.  However, my current plan is to use the SHA with which Molarity was recently published, so I think this is a non-issue for me.

**Comment by samreid** [comment]
Sounds great, thanks, closing.
