### ISSUE TITLE
What code is not covered by unit tests?

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#56]
The 1444 unit tests in dot are excellent, but it would be good to know exactly how much and what of the dot code is covered. Perhaps we could use an automated "code coverage" tool to identify what code is covered by the tests, or we could manually review it to discover it.  Ideally we would like to aim for 100% coverage eventually.

**Comment by ariel-phet** [comment]
Now that @jonathanolson is back full time it might be a good time to discuss this issue

**Comment by jonathanolson** [comment]
A tool to detect coverage would be great. I'm not familiar with any, would need to look into it.

**Comment by samreid** [comment]
https://github.com/gotwarlost/istanbul and http://blanketjs.org/ look like popular options for measuring code coverage.  From the istanbul docs:

> Yet another JS code coverage tool that computes statement, line, function and branch coverage with module loader hooks to transparently add coverage when running tests. Supports all JS coverage use cases including unit tests, server side functional tests and browser tests. Built for scale.

I don't have any familiarity with either of these tools.  The first question would be whether it integrates with our module loading patterns (e.g. if it can evaluate requirejs modules).

**Comment by samreid** [comment]
Istanbul steps to run in the browser are here: https://github.com/gotwarlost/istanbul/issues/16#issuecomment-18031171

For blanket-js you must add data-cover to scripts like this:
```html
<script src="my-library.js" data-cover></script>
```

**Comment by samreid** [comment]
@jonathanolson volunteered to investigate this within the next several weeks.

**Comment by jonathanolson** [comment]
Istanbul (easy to use) shows Dot's unit tests cover approximately 30-34% depending on the metric used, and shows what code has no coverage.

Built with --mangle=false, instrumented:
```sh
istanbul instrument dot.min.js > dot.min.instrumented.js
```
modified compiled unit test HTML to use the instrumented version (temporarily), ran, ```copy(__coverage__)``` pasted to a file (coverage*.json), then:
```sh
istanbul report --root directoryWithCoverageFiles --dir reportDirectory
```

shows:
![screen shot 2016-11-07 at 10 53 28 am](https://cloud.githubusercontent.com/assets/480878/20069107/7a9928fe-a4d8-11e6-8dc4-d45122837fee.png)

And detailed coverage:
![screen shot 2016-11-07 at 10 53 16 am](https://cloud.githubusercontent.com/assets/480878/20069125/86a739d8-a4d8-11e6-853b-2e19a2dff5d9.png)

There may be improved ways of creating copies of our source directories (with istanbul instrument) for sims, so that reports can separate files and ignore other dependencies. It should also be possible to integrate instrumentation into the sim/repo build process.

**Comment by jonathanolson** [comment]
See https://github.com/phetsims/chipper/issues/402 for general implementation of code coverage.

@samreid, should this be closed (and we can open up issues for improving unit test coverage?)

**Comment by samreid** [comment]
Thanks, we'll continue in https://github.com/phetsims/chipper/issues/402
