### ISSUE TITLE
Why do Ranges have default values?

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#57]
A range is a mathematical object of one of the following forms:
- The set of values for which a function is defined
- The difference between the maximum and minimum values (statistics)

Our range has a min, max and default value.  When @andrewadare and I were looking at reusing Range for specifying possible numeric values for PhET-iO, the "default value" sticks out like a sore thumb, and we are wondering why it is here in the first place.  It seems like it is here for convenience, but perhaps "Range" is not the best name for a class that also has a default value.

@andrewadare suggested using the term "Interval" to indicate something that has a min and max.

@andrewadare also indicated that a 3-arg Range constructor _seems like_ min, max, stepSize or min, stepSize, max, rather than a default value.

Not sure the best way to proceed, but it would be good to discuss.

**Comment by samreid** [comment]
One possibility would be to factor out another class, say "PureRange.js" which just has min and max.

**Comment by samreid** [comment]
Or Range.js has min and max, and RangeWithValue.js which extends Range.js and adds "value".

**Comment by pixelzoom** [comment]
+1 for RangeWithValue extends Range.

**Comment by andrewadare** [comment]
I will change Range to RangeWithValue, then go through and find all constructors taking only 2 args (min and max) and change those to Range. Following that sequence should be safe.

**Comment by andrewadare** [comment]
To minimize disruption, RangeWithValue has replaced Range everywhere, even where only two parameters are passed in. 

Moving forward, the plan should be to gradually replace the existing RangeWithValue instances with Range when it can be verified that no default value is being used.

As new code is written, the appropriate choice of Range vs. RangeWithValue should be made based on whether a defaultValue is needed.

**Comment by andrewadare** [comment]
It's been a week with no fallout whatsoever, so this one appears safe to close.

**Comment by samreid** [comment]
> Moving forward, the plan should be to gradually replace the existing RangeWithValue instances with Range when it can be verified that no default value is being used.

Do we have an issue for that?  Should we do it in a single pass?

**Comment by andrewadare** [comment]
Replacing RangeWithValue with Range in one pass would be tricky, because the defaultValue can potentially be used in ways that are hard to catch programatically as @pixelzoom pointed out two weeks ago in our dev meeting.

The suggestion I mentioned above pertained to case-by-case replacements, preferably by people who are familiar enough with a particular sim to catch cases where the default value of `defaultValue` (i.e. `min`) is being used implicitly.

**Comment by samreid** [comment]
> Replacing RangeWithValue with Range in one pass would be tricky, because the defaultValue can potentially be used in ways that are hard to catch programatically as @pixelzoom pointed out two weeks ago in our dev meeting.

Thanks, I had forgotten that we cannot simply check the constructor arguments.  I'm ok with the prescribed plan.

**Comment by pixelzoom** [comment]
Reopening.  

The replacement of `Range` with `RangeWithValue` apparently did not hit `@param` type expressions.  So now we have incorrect JSdoc.

For example, in beers-law-lab `BeersLawSolution`, we now have:

```js
   /**
   ...
55  * @param {Range} concentrationRange
   function BeersLawSolution( ..., concentrationRange, ... ) {
     ...
74   this.concentrationProperty = new Property( concentrationRange.defaultValue, {
    ...
}
```

Since we're using `concentrationRange.defaultValue` (line 74), its type should be `{RangeWidthValue}` (line 55). 

A quick search for ".defaultValue" shows that this problem occurs these places (possibly not a complete list):

- [ ] acid-base-solutions: ConcentrationSlider, StrengthSlider
- [ ] beers-law-lab: BeersLawSolution, Cuvette
- [ ] capacitor-law-basics: VoltageRange
- [ ] hookes-law-lab: Spring

**Comment by pixelzoom** [comment]
Type expression fixed were needed.  @jessegreenberg note that capacitor-law-basics.BatteryNode was touched. The others were my sims.  I think that's all of them, but not certain.  Will alert developers on Slack to be on the lookout.

Closing.
