### ISSUE TITLE
Add random number utilities (and seedable generator)

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/dot#7]
Mersenne Twister, random integers in a range, etc.

**Comment by pixelzoom** [comment]
@ariel-phet This is a nontrivial project. Please clarify why this was assigned to me, what the priority is, etc.

**Comment by samreid** [comment]
PhET-iO got reproducible (same seed) random number sequences in this issue https://github.com/phetsims/phet-io/issues/274

**Comment by ariel-phet** [comment]
@pixelzoom sorry, I thought I had commented on the issue but does not look like it took...

I was going through triaging issues and this was marked as high priority by you, but the issue is 3 years old...curious if it was still a priority, or if it should be addressed, brought up at developer meeting, etc. Just looking for a comment, no work.

**Comment by ariel-phet** [comment]
@samreid does this mean this issue is solved?

**Comment by samreid** [comment]
I don't recall the implementation details, but I'll assign to myself to investigate.

**Comment by samreid** [comment]
I recommend developers to skim dot/js/Random.js and we'll discuss at developer meeting if there is anything else to do here.

**Comment by jonathanolson** [comment]
Self-assigning for fleshing out Random.

**Comment by jonathanolson** [comment]
Looks fleshed out to me (probably a duplicate), closing.
